### ISSUE TITLE
Profile pictures don't stick around

### ISSUE THREAD

**Issue by markwhiting** [crowdresearch/daemo-forum#2]
I added a profile pictures and it showed up for a little bit but then stopped working.

I've done this several times with the same outcome.

**Comment by Nalinc** [comment]
Our forum is currently hosted on heroku which basically runs application slug. This makes storing static assets and file uploads impossible, unless we delegate this to some external storage.

We might use an **Amazon S3 bucket** in future, but that is something we haven't decided yet.
You may use 'System assigned profile picture' for the time being until we provide Gravatar support :)

**Comment by markwhiting** [comment]
OK. Thanks

**Comment by Nalinc** [comment]
Thanks for reopening @dmorina. 
IMO, this is possibly related to [dyno-sleeping and recharge behavior](https://devcenter.heroku.com/articles/dyno-sleeping).
So it might show the Gravatar when we initially set it, but that will eventually disappear when the dynos respawns(after 6 hours of sleep).
'System assigned profile picture'  should work for now until _we scale web dyno_ or _use s3_.
