### ISSUE TITLE
Transition forum to public content

### ISSUE THREAD

**Issue by dmorina** [crowdresearch/daemo-forum#4]
[copied from daemo]
In the same way many other crowd work forums are public, this would help people outside our community understand our culture.

It would also allow for public linking of documents stored within the forum, as was mentioned in https://github.com/crowdresearch/crowdsource-platform/issues/881.

**Comment by markwhiting** [comment]
The mentioned issue is: https://github.com/crowdresearch/crowdsource-platform/issues/881

**Comment by shirishgoyal** [comment]
Forum turned to public

**Comment by markwhiting** [comment]
@shirishgoyal so its all done with regard to the forum software?

I'll go through and check any content that could be problematic.
